# Generated by Django 6.0.2 on 2026-02-17 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='completed',
        ),
        migrations.AddField(
            model_name='job',
            name='source_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_jobs', to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
