# Generated by Django 6.0.2 on 2026-02-24 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_remove_job_completed_job_source_quote_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="number",
            field=models.CharField(
                db_index=True, default="J-0000-000", max_length=20, unique=True
            ),
            preserve_default=False,
        ),
    ]
