# Generated by Django 6.0.2 on 2026-02-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
