# Generated by Django 5.2.11 on 2026-03-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='number',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
