# Generated by Django 6.0.2 on 2026-02-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_invoice_job_invoice_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='type',
            field=models.CharField(choices=[('labour', 'Labour'), ('materials', 'Materials'), ('miscellaneous', 'Miscellaneous')], default='materials', max_length=20),
        ),
    ]
