# Generated by Django 6.0.2 on 2026-02-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoicelineitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
