# Generated by Django 6.0.2 on 2026-02-23 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_archived'),
        ('jobs', '0002_remove_job_completed_job_source_quote_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='jobs.job'),
        ),
    ]
