# Generated by Django 5.2.11 on 2026-02-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoice_subtotal_invoice_total_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_due',
        ),
    ]
