# Generated by Django 5.2.11 on 2026-02-28 20:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_remove_invoice_total_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('5.00'), '5%'), (Decimal('20.00'), '20%')], decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
    ]
