# Generated by Django 5.2.11 on 2026-02-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_invoice_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_instructions',
            field=models.TextField(blank=True),
        ),
    ]
