# Generated by Django 5.2.11 on 2026-03-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_invoice_notes_invoice_payment_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
