# Generated by Django 5.2.11 on 2026-03-03 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_bankdetails_user'),
        ('invoices', '0016_alter_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='company.bankdetails'),
        ),
    ]
