# Generated by Django 5.2.11 on 2026-03-03 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_bankdetails_user'),
        ('invoices', '0017_invoice_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='company.bankdetails'),
        ),
    ]
