# Generated by Django 6.0.2 on 2026-02-18 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('labour', 'Labour'), ('materials', 'Materials'), ('miscellaneous', 'Miscellaneous')], default='materials', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_templates', to='clients.client')),
            ],
        ),
    ]
