# Generated by Django 6.0.2 on 2026-02-18 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientitemtemplate',
            name='client',
        ),
        migrations.AddField(
            model_name='clientitemtemplate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_templates', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
