# Generated by Django 6.0.2 on 2026-02-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_remove_clientitemtemplate_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientitemtemplate',
            name='type',
            field=models.CharField(choices=[('Labour', 'Labour'), ('Materials', 'Materials'), ('Miscellaneous', 'Miscellaneous')], default='Materials', max_length=20),
        ),
    ]
