# Generated by Django 5.2.11 on 2026-02-27 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address_line', models.TextField(blank=True, max_length=100)),
                ('town', models.TextField(blank=True, max_length=100)),
                ('city', models.TextField(blank=True, max_length=100)),
                ('postcode', models.TextField(blank=True, max_length=20)),
                ('country', models.TextField(blank=True, default='UK', max_length=80)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('sort_code', models.CharField(blank=True, max_length=20)),
                ('payment_instructions', models.TextField(blank=True, help_text='Optional instructions for clients')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
