# Generated by Django 5.2.11 on 2026-02-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='city',
            new_name='town_or_city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='town',
        ),
    ]
