# Generated by Django 5.2.11 on 2026-02-28 20:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_bankdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='is_vat_registered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
    ]
