# Generated by Django 5.2.11 on 2026-02-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companydetails_is_vat_registered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='vat_rate',
        ),
    ]
