# Generated by Django 5.2.11 on 2026-03-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_companydetails_vat_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='payment_instructions',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='Optional instructions for clients'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='quote_terms',
            field=models.TextField(blank=True, help_text='Optional quoting terms for clients'),
        ),
    ]
