# Generated by Django 5.2.11 on 2026-03-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_bankdetails_payment_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='quote_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='quote_sequence_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
