# Generated by Django 5.2.11 on 2026-03-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_companydetails_quote_sequence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='quote_sequence_year',
            new_name='sequence_year',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='invoice_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='job_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
