# Generated by Django 6.0.2 on 2026-02-17 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_user'),
        ('jobs', '0002_remove_job_completed_job_source_quote_job_status'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='clients.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='jobs.job'),
        ),
    ]
