# Generated by Django 6.0.2 on 2026-02-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_client_alter_quote_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='job',
        ),
    ]
