# Generated by Django 6.0.2 on 2026-02-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_quote_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelineitem',
            name='type',
            field=models.CharField(choices=[('labour', 'Labour'), ('materials', 'Materials'), ('miscellaneous', 'Miscellaneous')], default='materials', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(),
        ),
    ]
