# Generated by Django 6.0.2 on 2026-02-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_alter_quote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelineitem',
            name='name',
            field=models.CharField(default='name', max_length=150),
            preserve_default=False,
        ),
    ]
