# Generated by Django 6.0.2 on 2026-02-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_alter_quotelineitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
