# Generated by Django 6.0.2 on 2026-02-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_quote_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='number',
            field=models.CharField(db_index=True, default='x', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
