# Generated by Django 6.0.2 on 2026-02-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_quote_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
