# Generated by Django 5.2.11 on 2026-02-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_quote_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelineitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
