# Generated by Django 5.2.11 on 2026-03-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_quote_subtotal_quote_total_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='terms',
            field=models.TextField(blank=True),
        ),
    ]
