# Generated by Django 5.2.11 on 2026-03-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_quote_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_terms',
            field=models.TextField(blank=True),
        ),
    ]
