# Generated by Django 5.2.11 on 2026-03-01 10:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_quote_notes_quote_quote_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='vat_rate',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('5.00'), '5%'), (Decimal('20.00'), '20%')], decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
    ]
