# Generated by Django 5.2.11 on 2026-03-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_quote_vat_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='terms',
        ),
    ]
