# Generated by Django 5.2.11 on 2026-03-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0017_remove_quote_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='total_due',
        ),
    ]
