# Generated by Django 5.2.11 on 2026-03-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0018_remove_quote_total_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='number',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
