# Generated by Django 5.2.11 on 2026-03-03 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_bankdetails_user'),
        ('quotes', '0019_alter_quote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='payment_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='company.bankdetails'),
        ),
    ]
